# Doctrine Configuration
doctrine:
    dbal:
        driver:     "%database_driver%"
        host:       "%database_host%"
        port:       "%database_port%"
        dbname:     "%database_name%"
        user:       "%database_user%"
        password:   "%database_password%"
        charset:    UTF8
        types:
            json:   Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~