# Twig Configuration
twig:
    debug:                    "%kernel.debug%"
    strict_variables:         "%kernel.debug%"

    base_template_class:      Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'